# Generated by Django 4.2.6 on 2023-10-25 14:04
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=15, verbose_name='Государственный номер')),
                ('brand', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
            ],
            options={
                'db_table': 'auto',
                'verbose_name': 'автомобиль',

            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('birth_date', models.DateTimeField(verbose_name='Дата рождения', blank=True, null=True)),
                ('passport_number', models.CharField(max_length=15, verbose_name='Номер паспорта')),
                ('home_address', models.TextField(verbose_name='Домашний адрес')),
                ('nationality', models.CharField(max_length=30, verbose_name='Национальность')),
            ],
            options={
                'db_table': 'custom_user',
                'verbose_name': 'Пользователь',

            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата конца', blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Auto',
                                           verbose_name='Автомобиль', related_name='ownerships')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CustomUser',
                                            verbose_name='Владелец', related_name='ownerships')),
            ],
            options={
                'db_table': 'ownership',
                'verbose_name': 'владение',

            },
        ),
        migrations.CreateModel(
            name='DrivingLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_num', models.CharField(max_length=10, verbose_name='Номер удостоверения')),
                ('type', models.CharField(max_length=10, verbose_name='Тип')),
                ('date', models.DateTimeField(verbose_name='Дата выдачи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CustomUser',
                                            verbose_name='Владелец', related_name='licences')),
            ],
            options={
                'db_table': 'driving_licence',
                'verbose_name': 'водительское удостоверение',

            },
        ),
    ]
