# Generated by Django 4.2.6 on 2023-11-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivinglicence',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
