# Generated by Django 4.2.7 on 2023-11-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='in_conferences', to='app.topic'),
        ),
    ]
