# Generated by Django 4.2.6 on 2023-10-27 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Автовладелец',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('фамилия', models.CharField(max_length=30)),
                ('имя', models.CharField(max_length=30)),
                ('дата_рождения', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Автомобиль',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('гос_номер', models.CharField(max_length=15)),
                ('марка', models.CharField(max_length=20)),
                ('модель', models.CharField(max_length=20)),
                ('цвет', models.CharField(blank=True, max_length=30, null=True)),
                ('владелец', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='автомобили', to='project_first_app.автовладелец')),
            ],
        ),
        migrations.CreateModel(
            name='Водительское_удостоверение',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('номер_удостоверения', models.CharField(max_length=10)),
                ('тип', models.CharField(max_length=10)),
                ('дата_выдачи', models.DateTimeField(blank=True, null=True)),
                ('владелец', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='водительские_удостоверения', to='project_first_app.автовладелец')),
            ],
        ),
        migrations.CreateModel(
            name='Владение',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_начала', models.DateTimeField(blank=True, null=True)),
                ('дата_окончания', models.DateTimeField(blank=True, null=True)),
                ('автовладелец', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='история_владения', to='project_first_app.автовладелец')),
                ('автомобиль', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='история_владельцев', to='project_first_app.автомобиль')),
            ],
        ),
    ]
