# Generated by Django 4.2.6 on 2023-10-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_car_carowner_driverlicense_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.carowner'),
        ),
    ]
