# Generated by Django 4.2.6 on 2023-10-28 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название конференции')),
                ('topics', models.TextField(verbose_name='Тематики конференции')),
                ('location', models.TextField(verbose_name='Место проведения')),
                ('location_description', models.TextField(verbose_name='Описание места проведения')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата завершения')),
                ('description', models.TextField(verbose_name='Описание конференции')),
                ('participation_conditions', models.TextField(verbose_name='Условия участия')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Рейтинг')),
                ('review_date', models.DateField(auto_now_add=True, verbose_name='Дата комментирования')),
                ('text', models.TextField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_conferences.conference', verbose_name='Конференция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommended_for_publication', models.BooleanField(default=False, verbose_name='Рекомендован к публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_conferences.author', verbose_name='Автор')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_conferences.conference', verbose_name='Конференция')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='registrations',
            field=models.ManyToManyField(through='list_of_conferences.AuthorRegistration', to='list_of_conferences.conference'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
